# Generated by Django 6.0.5 on 2026-05-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_covers/"),
        ),
    ]
