# Generated by Django 5.1 on 2026-05-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blog_id"),
        ("blogs", "0002_blog_cover_image"),
    ]

    operations = []
