# Generated by Django 6.0.5 on 2026-05-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_bookmark_comment_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="is_liked",
            field=models.BooleanField(default=True),
        ),
    ]
