# Generated by Django 6.0.5 on 2026-05-29 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_merge_0002_alter_blog_id_0002_blog_cover_image"),
        ("blogs", "0004_alter_like_is_liked"),
    ]

    operations = []
